---
name: Build and Push Docker Image, then Deploy to ECS

on:
  push:
    branches:
      - main  # Triggers the workflow on merge to `main` branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  

    - name: Install dependencies and run unit tests
      run: | # install dependencies and run unit tests
        pip install -r requirements.txt  
        python -m unittest 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 

    - name: Build and push Docker image
      run: | # Push the image to Docker Hub
        docker build -t my_personal/my-app .  
        docker push my_personal/my-app  

  deploy:
    if: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # or just use OIDC and not need these ¯\_(ツ)_/¯
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # or just use OIDC and not need these ¯\_(ツ)_/¯
        aws-region: us-east-1  

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.15.0 

    - name: Initialize Terraform
      run: terraform init

    - name: Deploy ECS Service
      run: terraform apply -auto-approve